import { Course } from "../types/entities/courses";

export const Niveau2coursesData: { [week: string]: Course[] } = {
  "26-30 Nov 2024": [
    {
      code: "SCAR 212",
      title: "Les urgences cardiovasculaires",
      date: "26 Nov",
      time: "14H-16H30",
      resident: "Dr OUANKOU C",
      instructors: ["Pr HAMADOU BA", "Pr BOOMBHI J", "Dr OUANKOU C"],
      observation: "Séminaire",
    },
    {
      code: "SCAR 212",
      title: "Syndrome coronaire aigu",
      date: "27 Nov",
      time: "13H00-15H00",
      resident: "Dr Amina Babalala",
      instructors: ["Dr Amina Babalala", "Pr MENANGA A", "Dr OWONA"],
      observation: "Séminaire",
    },
    {
      code: "SCAR 211",
      title: "Les cardiopathies primitives et acquises",
      date: "29 Nov",
      time: "16H00-17H30",
      resident: "Dr Nzongang Hursul",
      instructors: ["Dr Nzongang Hursul", "Pr DZUDZIE A", "Pr BOOMBHI"],
      observation: "Séminaire",
    },
  ],
  "06-10 Jan 2025": [
    {
      code: "SCAR 211",
      title: "Insuffisance cardiaque",
      date: "06 Jan",
      time: "13H00-17H00",
      resident: "Dr Essola Andiolo",
      instructors: ["Dr Essola Andiolo", "Dr Gadkang Anicet", "Dr Mevono Nkou"],
      observation: "Séminaire",
    },
    {
      code: "SCAR 211",
      title: "Péricardites",
      date: "07 Jan",
      time: "15H30-17H30",
      resident: "Dr Claudine Jessica Yondo",
      instructors: ["Dr Claudine Jessica Yondo", "Pr KUATE", "Dr EBENE"],
      observation: "Séminaire",
    },
  ],
  "27-31 Jan 2025": [
    {
      code: "SCAR 213",
      title: "Hypertension artérielle",
      date: "27 Jan",
      time: "13H00-17H00",
      resident: "Dr Essola Andiolo Ornella",
      instructors: ["Dr Essola Andiolo", "Dr Gadkang Ladibe Anicet"],
      observation: "Séminaire",
    },
    {
      code: "SCAR 213",
      title: "Anévrysme de l’aorte",
      date: "29 Jan",
      time: "13H00-15H00",
      resident: "Dr Anyuouzo’o Ella Simon",
      instructors: ["Dr Anyuouzo’o Ella Simon", "Pr NDONGO S", "Dr FOKOU M"],
      observation: "Séminaire",
    },
  ],
};

export const Niveau3coursesData: { [week: string]: Course[] } = {
  "16-19 Dec 2024": [
    {
      code: "SCAR 313",
      title: "Tétralogie de Fallot",
      date: "16 Dec",
      time: "13H00-15H00",
      resident: "Dr Balomog Audrey",
      instructors: ["Dr Balomog Audrey", "Pr MENANGA A", "Pr BOOMBHI J"],
      observation: "Séminaire",
    },
    {
      code: "SCAR 313",
      title: "Transposition des gros Vaisseaux",
      date: "17 Dec",
      time: "14H00-15H00",
      resident: "Dr Bidjogo Atangana",
      instructors: ["Dr Bidjogo Atangana", "Pr NDONGO S", "Dr OWONA"],
      observation: "Séminaire",
    },
    {
      code: "SCAR 313",
      title: "Anomalies du retour veineux pulmonaire",
      date: "17 Dec",
      time: "15H00-16H00",
      resident: "Dr Daouda Sadou",
      instructors: [
        "Dr Daouda Sadou",
        "Pr CHELO D",
        "Pr NDONGO S",
        "Dr OWONA A",
      ],
      observation: "Séminaire",
    },
    {
      code: "SCAR 313",
      title: "Coarcation de l’aorte",
      date: "18 Dec",
      time: "14H00-15H00",
      resident: "Dr Elouna Valentin",
      instructors: ["Dr Elouna Valentin", "Pr BOOMBHI J", "Dr OWONA A"],
      observation: "Séminaire",
    },
  ],
  "20-27 Dec 2024": [
    {
      code: "SCAR 311",
      title:
        "Echocardiographie doppler : Étude de la fonction systolique et diastolique",
      date: "20 Dec",
      time: "13H00-17H00",
      resident: "N/A",
      instructors: ["Pr BOOMBHI J", "Dr MINTOM P"],
      observation: "Séminaire",
    },
    {
      code: "SCAR 311",
      title: "Echocardiographie doppler dans les valvulopathies",
      date: "23 Dec",
      time: "13H00-17H00",
      resident: "N/A",
      instructors: ["Pr HAMADOU BA", "Pr BOOMBHI J", "Dr NDOBO"],
      observation: "Séminaire",
    },
    {
      code: "SCAR 311",
      title: "Echographie trans-oesophagienne & Echographie de stress",
      date: "26 Dec",
      time: "15H00-17H00",
      resident: "N/A",
      instructors: ["Pr NGANOU C", "Dr MINTOM P"],
      observation: "Séminaire",
    },
  ],
};
