import { EnseignantsType } from "../types/entities/enseignants";

const predefinedEnseignants: EnseignantsType[] = [
  {
    id: 1,
    nom: "BOOMBHI",
    photo: "/images/enseignants/BOOMBHI.JPG",
    grade: "Professeur en Radiologie Diagnostique",
    departement: "Radiologie Diagnostique",
    faculte: "Faculté de Médecine",
    universite: "Université de Dakar",
    pays: "Sénégal",
  },
  {
    id: 2,
    nom: "CHELO",
    photo: "/images/enseignants/CHELO.JPG",
    grade: "Professeur en Radiologie Interventionnelle",
    departement: "Radiologie Interventionnelle",
    faculte: "Faculté des Sciences Médicales",
    universite: "Université de Paris",
    pays: "France",
  },
  {
    id: 3,
    nom: "DZUDIE",
    photo: "/images/enseignants/DZUDIE.JPG",
    grade: "Professeur en Imagerie Médicale",
    departement: "Imagerie Médicale",
    faculte: "Faculté de Chirurgie et Médecine",
    universite: "Université de Yaoundé",
    pays: "Cameroun",
  },
  {
    id: 4,
    nom: "EBENE MANON",
    photo: "/images/enseignants/EBENE_MANON.JPG",
    grade: "Professeur en Radiologie Pédiatrique",
    departement: "Radiologie Pédiatrique",
    faculte: "Faculté des Sciences Médicales",
    universite: "Université de Tunis",
    pays: "Tunisie",
  },
  {
    id: 5,
    nom: "HAMADOU BA",
    photo: "/images/enseignants/HAMADOU_BA.JPG",
    grade: "Professeur en Imagerie Cardiaque",
    departement: "Imagerie Cardiaque",
    faculte: "Faculté de Médecine",
    universite: "Université de Pékin",
    pays: "Chine",
  },
  {
    id: 5,
    nom: "KAMDEM FELICITE",
    photo: "/images/enseignants/KAMDEM_FELICITE.JPG",
    grade: "Professeur en Imagerie Cardiaque",
    departement: "Imagerie Cardiaque",
    faculte: "Faculté de Médecine",
    universite: "Université de Pékin",
    pays: "Chine",
  },
  {
    id: 5,
    nom: "KUATE",
    photo: "/images/enseignants/KUATE.JPG",
    grade: "Professeur en Imagerie Cardiaque",
    departement: "Imagerie Cardiaque",
    faculte: "Faculté de Médecine",
    universite: "Université de Pékin",
    pays: "Chine",
  },
  {
    id: 5,
    nom: "MENANGA",
    photo: "/images/enseignants/MENANGA.JPG",
    grade: "Professeur en Imagerie Cardiaque",
    departement: "Imagerie Cardiaque",
    faculte: "Faculté de Médecine",
    universite: "Université de Pékin",
    pays: "Chine",
  },
  {
    id: 5,
    nom: "NGANOU",
    photo: "/images/enseignants/NGANOU.JPG",
    grade: "Professeur en Imagerie Cardiaque",
    departement: "Imagerie Cardiaque",
    faculte: "Faculté de Médecine",
    universite: "Université de Pékin",
    pays: "Chine",
  },
  {
    id: 5,
    nom: "NGONGANG OUANKOU",
    photo: "/images/enseignants/NGONGANG_OUANKOU.JPG",
    grade: "Professeur en Imagerie Cardiaque",
    departement: "Imagerie Cardiaque",
    faculte: "Faculté de Médecine",
    universite: "Université de Pékin",
    pays: "Chine",
  },
];

export default predefinedEnseignants;
