import { EnseignantsType } from "../types/entities/enseignants";

const predefinedEnseignants: EnseignantsType[] = [
  {
    id: 1,
    nom: "Pr BOOMHI Jérôme",
    photo: "/images/enseignants/BOOMBHI.JPG",
    grade: "Maitre de Conférences Agrégé",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 2,
    nom: "Pr CHELO David",
    photo: "/images/enseignants/CHELO.JPG",
    grade: "Professeur",
    departement: "Départment de Pédiatrie",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 3,
    nom: "Pr DZUDIE TAMDKA Anastase",
    photo: "/images/enseignants/DZUDIE.JPG",
    grade: "Maitre de Conférences",
    departement: "Département de Physiologie Humaine",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 4,
    nom: "Dr EBENE MANON Guillaume",
    photo: "/images/enseignants/EBENE_MANON.JPG",
    grade: "Assistant",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 5,
    nom: "Pr HAMADAOU BA",
    photo: "/images/enseignants/HAMADOU_BA.JPG",
    grade: "Maitre de Conférences Agrégé",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 6,
    nom: "Dr FOKOU",
    photo: "",
    grade: "Professeur en Imagerie Cardiaque",
    departement: "Département de Chirurgie",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 7,
    nom: "Pr KUATE née MFEUKEU KWA Liliane Claudine",
    photo: "/images/enseignants/KUATE.JPG",
    grade: "Maitre de Conférences",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 8,
    nom: "Pr MENANGA Alain Patrick",
    photo: "/images/enseignants/MENANGA.JPG",
    grade: "Professeur",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 9,
    nom: "Pr NGANOU Chris Nadège",
    photo: "/images/enseignants/NGANOU.JPG",
    grade: "Maitre de Conférences Agrégé",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 10,
    nom: "Dr NGONGANG OUANKOU Christian",
    photo: "/images/enseignants/NGONGANG_OUANKOU.JPG",
    grade: "Chargé de cours",
    departement: "",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 11,
    nom: "Dr NDOBO épouse KOE Valérie Danielle",
    photo: "",
    grade: "Chargé de cours",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 12,
    nom: "Pr NDONGO AMOUGOU Sylvie Laurette ",
    photo: "",
    grade: "Maitre de Conférences",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 13,
    nom: "Dr MINTOM MEDJO Pierre Didier",
    photo: "",
    grade: "Chargé de cours",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
  {
    id: 14,
    nom: "Dr OWONO NGABEDE Amalia Ariane",
    photo: "",
    grade: "Maitre Assistant",
    departement: "Département de Médecine Interne et Spécialités",
    faculte: "Faculté de Médecine et des Sciences Biomédicales",
    universite: "Université de Yaoundé 1",
    pays: "Cameroun",
  },
];

export default predefinedEnseignants;
