import { EnseignantsType } from "../types/entities/enseignants";

export const predefinedEtudiantsNiveau1: EnseignantsType[] = [];

export const predefinedEtudiantsNiveau2: EnseignantsType[] = [
  {
    id: 1,
    nom: "AMINA BABALALA",
    email: "babamina348@gmail.com",
    numero: "656814075",
    matricule: "",
  },
  {
    id: 2,
    nom: "ANYOUZO’O ELLA Simon",
    email: "simonella297@gmail.com",
    numero: "697606590",
    matricule: "",
  },
  {
    id: 3,
    nom: "ATEBA ONDIGUI Serge Patrick",
    email: "",
    numero: "691216978",
    matricule: "",
  },
  {
    id: 4,
    nom: "BELLA Arthur Hilaire William",
    email: "wbella52@gmail.com",
    numero: "698899701",
    matricule: "",
  },
  {
    id: 5,
    nom: "YONDO NDEDI Claudine Jessica",
    email: "ndedijessica@gmail.com",
    numero: "695831776",
    matricule: "",
  },
  {
    id: 6,
    nom: "ESSOLA ANDIOLO Ornella Kelyane",
    email: "Kelyaneessola0@gmail.com",
    numero: "693733624",
    matricule: "",
  },
  {
    id: 7,
    nom: "GAKDANG LADIBE Anicet",
    email: "ladibegakdang@gmail.com",
    numero: "697871137",
    matricule: "",
  },
  {
    id: 8,
    nom: "KONGNYUY KWANSAH Larisa Epse MBUA",
    email: "naslarysa@yahoo.com",
    numero: "676553658",
    matricule: "",
  },
  {
    id: 9,
    nom: "MADJILE BABA Lynda",
    email: "lyndababa26@gmail.com",
    numero: "696112935",
    matricule: "",
  },
  {
    id: 10,
    nom: "MEVONO NKOU Joel Lionel",
    email: "",
    numero: "693541882",
    matricule: "",
  },
  {
    id: 11,
    nom: "NGONO Jeanine Michelle",
    email: "michellengono3@gmail.com",
    numero: "694105819",
    matricule: "",
  },
  {
    id: 12,
    nom: "NOUEBISSI PFEUDIE Linda EP NGADOU",
    email: "",
    numero: "678128757",
    matricule: "",
  },
  {
    id: 13,
    nom: "NOUGA Nolwenn Suzanne",
    email: "nolwennsuzannenouga@gmail.com",
    numero: "699781143",
    matricule: "",
  },
  {
    id: 14,
    nom: "NZONGANG Hursul Geffried",
    email: "hursulnzongang@gmail.com",
    numero: "693642836",
    matricule: "",
  },
  {
    id: 15,
    nom: "SHAFRAOU DJALLO",
    email: "shafrydjallo@gmail.com",
    numero: "694538140",
    matricule: "",
  },
];

export const predefinedEtudiantsNiveau3: EnseignantsType[] = [
  {
    id: 1,
    nom: "BALOMOG Audrey",
    email: "jesaubry@gmail.com",
    numero: "698681276",
    matricule: "",
  },
  {
    id: 2,
    nom: "BIDJOGO ATANGANA",
    email: "elgabynho10@yahoo.com",
    numero: "698049853",
    matricule: "",
  },
  {
    id: 3,
    nom: "DAOUDA SADOU Adal",
    email: "daoudasadouadal@gmail.com",
    numero: "694843096",
    matricule: "",
  },
  {
    id: 4,
    nom: "ELAD JUDE FOTABONG",
    email: "judoforchrist@gmail.com",
    numero: "680002999",
    matricule: "",
  },
  {
    id: 5,
    nom: "ELOUNA ELOUNA Valentin",
    email: "valentinelounaelouna@gmail.com",
    numero: "697571506",
    matricule: "",
  },
  {
    id: 6,
    nom: "HAMIKA MOLLI Johan",
    email: "joehamika@gmail.com",
    numero: "696494053",
    matricule: "",
  },
  {
    id: 7,
    nom: "HOURI BOUKAR",
    email: "houriboukar@yahoo.fr",
    numero: "694426923",
    matricule: "",
  },
  {
    id: 8,
    nom: "INENGUINI Orphe",
    email: "orpheb@yahoo.fr",
    numero: "697392368",
    matricule: "",
  },
  {
    id: 9,
    nom: "MAGANG SADO Ange",
    email: "angedallonnez22@gmail.com",
    numero: "",
    matricule: "",
  },
  {
    id: 10,
    nom: "MEFO KUE Didi",
    email: "didimefo92@gmail.com",
    numero: "693291174",
    matricule: "",
  },
  {
    id: 11,
    nom: "MOHAMADOU Djibrilla Sali",
    email: "modjisab6@gmail.com",
    numero: "696273453",
    matricule: "",
  },
  {
    id: 12,
    nom: "MULENDE NGANGUE Brenda",
    email: "nganguelise1@gmail.com",
    numero: "694196151",
    matricule: "",
  },
  {
    id: 13,
    nom: "NJIKI KOUATCHOU Sandra Jessica",
    email: "sandrajessicanjiki@yahoo.fr",
    numero: "697031210",
    matricule: "",
  },
  {
    id: 14,
    nom: "UM BOOCK Jeanne",
    email: "ubveronik@gmail.com",
    numero: "694210018",
    matricule: "",
  },
  {
    id: 15,
    nom: "ZANG EFFOUDOU Odile",
    email: "cyrielle.zang@gmail.com",
    numero: "693411576",
    matricule: "",
  },
  {
    id: 16,
    nom: "TASONG MBOSSO Loïc",
    email: "tasongloic00@gmail.com",
    numero: "696776138",
    matricule: "",
  },
];

export const predefinedEtudiantsNiveau4: EnseignantsType[] = [];
